### ISSUE TITLE
没有专用的TPU报错了，如何在常用的X86的linux 机器上跑呢？

### ISSUE THREAD

**Issue by koala9527** [ZillaRU/roop_face#1]
报错内容：
```
(venv) root@koala9527:/home/jijiwaiwai/my-project/roop_face# python3 demo_app.py 
Traceback (most recent call last):
  File "/home/jijiwaiwai/my-project/roop_face/demo_app.py", line 7, in <module>
    from roop import setup_model, swap_face
  File "/home/jijiwaiwai/my-project/roop_face/roop/__init__.py", line 2, in <module>
    from .swapper_main import swap_face
  File "/home/jijiwaiwai/my-project/roop_face/roop/swapper_main.py", line 19, in <module>
    face_swapper_tpu = INSwapper("./bmodel_files/inswapper_128_F16.bmodel")
  File "/home/jijiwaiwai/my-project/roop_face/roop/inswappertpu.py", line 15, in __init__
    self.session = EngineOV(self.model_file)
  File "/home/jijiwaiwai/my-project/roop_face/roop/npuengine.py", line 13, in __init__
    self.model = SGInfer(model_path , batch=batch, devices=[device_id])
  File "/home/jijiwaiwai/my-project/roop_face/venv/lib/python3.10/site-packages/tpu_perf/infer.py", line 68, in __init__
    self.__class__.__lib = ct.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbmlib.so.0: cannot open shared object file: No such file or directory
Exception ignored in: <function SGInfer.__del__ at 0x7e29074af520>
Traceback (most recent call last):
  File "/home/jijiwaiwai/my-project/roop_face/venv/lib/python3.10/site-packages/tpu_perf/infer.py", line 116, in __del__
    self.__lib.runner_stop(self.runner_id)
AttributeError: 'NoneType' object has no attribute 'runner_stop'

```

**Comment by ZillaRU** [comment]
这就是给我司自研tpu做的适配。不适配专用tpu的代码去搜别的项目就好了。😆
